# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7392d45c902bee4ab61422dd362e9c3995689e7a3d1068aee2d923e27e14e656b53e5a83ed8e9e7672b3040ac76e869c3552bf6792c94c3be9bb169f2b9eb99

test:
  secret_key_base: 041e98331f582a6dd1f9f4b5f9f8f1eb772f3488a6c29b6c949df30451b2f0c35ac3dbcf7034222c1a6a949d89234ee74ba0a89ed1dd1a3992fecc6d1d27acaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
